service: lunch-menu-finder

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2
  environment:
    NAVER_CLIENT_ID: ${env:NAVER_CLIENT_ID}
    NAVER_CLIENT_SECRET: ${env:NAVER_CLIENT_SECRET}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    KAKAO_REST_API_KEY: ${env:KAKAO_REST_API_KEY}

functions:
  api:
    handler: fastapi_app.main.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: lunch-menu-finder-frontend-hjkim909
      localDir: frontend/dist
      params:
        - index.html:
            CacheControl: 'no-cache, no-store, must-revalidate'
        - "*.js":
            CacheControl: 'public, max-age=31536000'
        - "*.css":
            CacheControl: 'public, max-age=31536000'
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lunch-menu-finder-frontend-hjkim909
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: arn:aws:s3:::lunch-menu-finder-frontend-hjkim909/*

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: lunch-menu-finder-frontend-hjkim909.s3-website.ap-northeast-2.amazonaws.com
              Id: FrontendOrigin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: FrontendOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

  Outputs:
    CloudFrontURL:
      Value: !GetAtt CloudFrontDistribution.DomainName
